Repository DeveloperAcademy-POSTECH/MC3-Team11-DBAL, pull requests merged in 2022-08, with the labels that each got.

#102 Firebase 관련 함수들 추가
  GiveCake/GiveCake.xcodeproj/project.pbxproj
  GiveCake/GiveCake/Sources/AppDelegate.swift
  GiveCake/GiveCake/Sources/Global/Manager/FirebaseManager.swift
  GiveCake/GiveCake/Sources/Global/Manager/FirebaseStorageManager.swift
  GiveCake/GiveCake/Sources/Model/FirebaseModel.swift
  GiveCake/GiveCake/Sources/TestGround/GiverMessageGround.storyboard
  GiveCake/GiveCake/Sources/TestGround/GiverMessageGroundVC.swift
Labels: ✅ ADD, 😀 Ground

#103 관리자 홈 세팅뷰 UIView들 모서리 넣고 올립니다
  GiveCake/GiveCake/Sources/SceneDelegate.swift
  GiveCake/GiveCake/Sources/Screen/Admin/AdminHome.storyboard
  GiveCake/GiveCake/Sources/Screen/Admin/AdminHomeSetting.storyboard
  GiveCake/GiveCake/Sources/ViewController/Admin/AdminHomeSettingVC.swift
Labels: ✅ ADD, 😀 Hans

#107 CloudKit 잔재 불태워버리기
  GiveCake/GiveCake.xcodeproj/project.pbxproj
  GiveCake/GiveCake/GiveCake.entitlements
  GiveCake/GiveCake/Sources/Global/Manager/CloudKitManager.swift
Labels: 🔥 DEL, 😀 Ground

#108 Revert "CloudKit 잔재 불태워버리기"
  GiveCake/GiveCake.xcodeproj/project.pbxproj
  GiveCake/GiveCake/GiveCake.entitlements
  GiveCake/GiveCake/Sources/Global/Manager/CloudKitManager.swift
Labels: 😀 Ground

#110 Firestore와 UI 연결
  GiveCake/GiveCake.xcodeproj/project.pbxproj
  GiveCake/GiveCake/Sources/Global/Manager/FirebaseManager.swift
  GiveCake/GiveCake/Sources/Model/MessageModel.swift
  GiveCake/GiveCake/Sources/ViewController/Giver/GiverLoginVC.swift
  GiveCake/GiveCake/Sources/ViewController/Giver/GiverMessageVC.swift
  GiveCake/GiveCake/Sources/ViewController/Giver/GiverMessageWriteVC.swift
  GiveCake/GiveCake/Sources/ViewController/Taker/TakerLoginVC.swift
  GiveCake/GiveCake/Sources/ViewController/Taker/TakerMessageVC.swift
  GiveCake/GiveCake/Sources/ViewController/Taker/TakerMessageWriteVC.swift
Labels: ✨ FEAT, 😀 Ground
