Repository DeveloperAcademy-POSTECH/MC3-Team11-DBAL, pull requests merged in 2022-07, with the labels that each got.

#8 Issue Templates 추가 생성
  .github/ISSUE_TEMPLATE/add-issue.md
  .github/ISSUE_TEMPLATE/chore-issue.md
  .github/ISSUE_TEMPLATE/correct-issue.md
  .github/ISSUE_TEMPLATE/del-issue.md
  .github/ISSUE_TEMPLATE/docs-issue.md
  .github/ISSUE_TEMPLATE/feat-issue.md
  .github/ISSUE_TEMPLATE/fix-issue.md
  .github/ISSUE_TEMPLATE/improve-issue.md
  .github/ISSUE_TEMPLATE/mod-issue.md
  .github/ISSUE_TEMPLATE/move-issue.md
  .github/ISSUE_TEMPLATE/refactor-issue.md
  .github/ISSUE_TEMPLATE/tip-issue.md
Labels: 📝 DOCS

#31 [feat] #22 GiverLogin 구현
  GiveCake/GiveCake/Sources/Screen/GiverLogin.storyboard
  GiveCake/GiveCake/Sources/ViewController/GiverLoginVC.swift
Labels: ✨ FEAT, 😀 Ssoo

#25 Giver의 메시지 관련 UI 구현
  GiveCake/GiveCake.xcodeproj/project.pbxproj
  GiveCake/GiveCake/Sources/Screen/GiverMessage.storyboard
  GiveCake/GiveCake/Sources/ViewController/GiverMessageVC.swift
  GiveCake/GiveCake/Sources/ViewController/GiverMessageVC/Controller/GiverMessageReceiveVC.swift
  GiveCake/GiveCake/Sources/ViewController/GiverMessageVC/Controller/GiverMessageTableVC.swift
  GiveCake/GiveCake/Sources/ViewController/GiverMessageVC/Controller/GiverMesssageWriteVC.swift
  GiveCake/GiveCake/Sources/ViewController/GiverMessageVC/DummyModel/GiverMessageDummyModel.swift
  GiveCake/GiveCake/Sources/ViewController/GiverMessageVC/View/GiverMessageBaseTableViewCell.swift
  GiveCake/GiveCake/Sources/ViewController/GiverMessageVC/View/GiverMessageTableViewCell.swift
Labels: ✨ FEAT, 😀 Ground

#29 CloudKit Manager 구현
  GiveCake/GiveCake.xcodeproj/project.pbxproj
  GiveCake/GiveCake/Sources/AppDelegate.swift
  GiveCake/GiveCake/Sources/Global/Manager/CloudKitManager.swift
  GiveCake/GiveCake/Sources/ViewController/GiverMessageVC/Controller/GiverMesssageWriteVC.swift
Labels: ✨ FEAT, 😀 Ground

#44 스프린트1 작업 합치기
  GiveCake/GiveCake.xcodeproj/project.pbxproj
  GiveCake/GiveCake/Resources/Assets.xcassets/B-DayKids_symbol-3.imageset/B-DayKids_symbol.svg
  GiveCake/GiveCake/Resources/Assets.xcassets/B-DayKids_symbol-3.imageset/Contents.json
  GiveCake/GiveCake/Sources/Global/Extensions/ColorExtension.swift
  GiveCake/GiveCake/Sources/Screen/GiverHome.storyboard
  GiveCake/GiveCake/Sources/ViewController/GiverHomeVC.swift
Labels: ✅ ADD, 😀 Hans, 😀 Ground

#57 쑤, 한스 사진(임시) 프로젝트에 추가
  GiveCake/GiveCake/Resources/Assets.xcassets/feed_hans_image.imageset/Contents.json
  GiveCake/GiveCake/Resources/Assets.xcassets/feed_hans_image.imageset/hans.jpeg
  GiveCake/GiveCake/Resources/Assets.xcassets/feed_ssoo_image.imageset/Contents.json
  GiveCake/GiveCake/Resources/Assets.xcassets/feed_ssoo_image.imageset/ssoo.jpeg
  GiveCake/GiveCake/Sources/Model/GiverFeedModel.swift
Labels: ✅ ADD, 😀 Ground

#61 Taker쪽 메세지뷰 구현 완료
  GiveCake/GiveCake.xcodeproj/project.pbxproj
  GiveCake/GiveCake/Sources/Model/TakerMessageModel.swift
  GiveCake/GiveCake/Sources/Screen/Admin/AdminMessage.storyboard
  GiveCake/GiveCake/Sources/Screen/Giver/GiverFeed.storyboard
  GiveCake/GiveCake/Sources/Screen/MessageCell.xib
  GiveCake/GiveCake/Sources/Screen/Taker/TakerMessage.storyboard
  GiveCake/GiveCake/Sources/Screen/Taker/TakerMessageWrite.storyboard
  GiveCake/GiveCake/Sources/ViewController/Admin/AdminMessageVC.swift
  GiveCake/GiveCake/Sources/ViewController/MessageCell.swift
  GiveCake/GiveCake/Sources/ViewController/Taker/TakerMessageVC.swift
  GiveCake/GiveCake/Sources/ViewController/Taker/TakerMessageWriteVC.swift
Labels: ✨ FEAT, 😀 Dophi

#87 Firebase 초기 세팅
  GiveCake/GiveCake.xcodeproj/project.pbxproj
  GiveCake/GiveCake.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GiveCake/GiveCake/Sources/AppDelegate.swift
Labels: ✅ ADD, 😀 Ground

#90 firebase plist 추가
  GiveCake/GiveCake.xcodeproj/project.pbxproj
  GiveCake/GiveCake/GoogleService-Info.plist
Labels: 🐛 FIX, 😀 Ground

#98 기부현황 설정하기 모달뷰에 들어가는 Label, Textfiled, Btn 배치 했습니다.
  GiveCake/GiveCake.xcodeproj/project.pbxproj
  GiveCake/GiveCake/Sources/SceneDelegate.swift
  GiveCake/GiveCake/Sources/Screen/Admin/AdminHome.storyboard
  GiveCake/GiveCake/Sources/Screen/Admin/AdminHomeSetting.storyboard
  GiveCake/GiveCake/Sources/ViewController/Admin/AdminHomeSettingVC.swift
  GiveCake/GiveCake/Sources/ViewController/Admin/AdminHomeVC 2.swift
  GiveCake/GiveCake/Sources/ViewController/Admin/AdminHomeVC.swift
Labels: ✨ FEAT, 😀 Hans
